name = "solid-lean"
version = "0.1.0"
defaultTargets = ["Solid"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0"

[[lean_lib]]
name = "Solid"
roots = ["Solid"]

[[lean_lib]]
name = "Palomar"
roots = ["Palomar.Challenge", "Palomar.Statement", "Palomar.Solution"]
globs = ["Palomar.+"]

[[require]]
name = "Foundation"
git = "https://github.com/FormalizedFormalLogic/Foundation.git"
rev = "33f9f6859650a440dad9fd14aaa300553ba65e44"
